# Generated by Django 4.0.6 on 2022-07-14 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_format_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.card'),
            preserve_default=False,
        ),
    ]
