# Generated by Django 4.0.6 on 2022-07-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_format_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='sets',
            field=models.ManyToManyField(to='main_app.set'),
        ),
    ]
